env:
  - name: DB_HOST
    value: "mysql"
  - name: DB_USER
    value: "root"
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mysql-secret
        key: MYSQL_ROOT_PASSWORD
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: mysql-secret
        key: MYSQL_DATABASE
  - name: REDIS_HOST
    value: "redis"
  - name: REDIS_PORT
    value: "6379"